version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pharmacy-management-service
    image: mye-payment-service
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    ports:
      - "8080:8080"
