-- CreateEnum
CREATE TYPE "EmailSource" AS ENUM ('USER_VERIFICATION', 'PASSWORD_RESET', 'CHANGE_PASSWORD', 'ACCOUNT_ACTIVATION', 'WELCOME_EMAIL', 'ACCOUNT_DEACTIVATION', 'ORDER_CONFIRMATION', 'ORDER_SHIPPED', 'ORDER_DELIVERED', 'ORDER_CANCELLED', 'CART_ABANDONMENT_REMINDER', 'PROMOTIONAL_OFFER', 'NEWSLETTER', 'PRODUCT_RECOMMENDATION', 'REFUND_CONFIRMATION', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED');

-- CreateTable
CREATE TABLE "Email" (
    "id" TEXT NOT NULL,
    "sender" TEXT NOT NULL,
    "recipient" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "source" "EmailSource" NOT NULL,
    "sendAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Email_pkey" PRIMARY KEY ("id")
);
